# Generated by Django 5.2.1 on 2026-03-11 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("Telegram", "Telegram"), ("VK", "VK")], max_length=32
                    ),
                ),
                ("handle", models.CharField(blank=True, max_length=255)),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("last_message", models.TextField(blank=True)),
                ("last_time", models.CharField(blank=True, max_length=64)),
                ("unread", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("url", models.URLField(max_length=1000)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="MaterialReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("unit_price", models.CharField(max_length=64)),
                ("stock", models.CharField(max_length=64)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Готовый комплект", "Готовый комплект"),
                            ("Под заказ", "Под заказ"),
                            ("Реконструкция", "Реконструкция"),
                        ],
                        max_length=32,
                    ),
                ),
                ("category", models.CharField(max_length=128)),
                ("era", models.CharField(max_length=64)),
                ("material", models.CharField(max_length=128)),
                ("sizes", models.JSONField(default=list)),
                ("price_from", models.PositiveIntegerField()),
                ("lead_time", models.CharField(max_length=64)),
                ("weight", models.CharField(max_length=64)),
                ("popularity", models.PositiveIntegerField(default=0)),
                ("protection_class", models.CharField(max_length=64)),
                ("history", models.TextField()),
                ("description", models.JSONField(default=list)),
                ("image", models.URLField(max_length=1000)),
                ("gallery", models.JSONField(default=list)),
                ("badge", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Новый", "Новый"),
                            ("Подтверждён", "Подтверждён"),
                            ("В производстве", "В производстве"),
                            ("Готов", "Готов"),
                            ("Доставлен", "Доставлен"),
                        ],
                        default="Новый",
                        max_length=32,
                    ),
                ),
                ("total_cost", models.PositiveIntegerField(default=0)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("items", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="workshop.client",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="workshop.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("client", "client"), ("manager", "manager")],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField()),
                ("external_message_id", models.CharField(blank=True, max_length=128)),
                ("sent_at_label", models.CharField(blank=True, max_length=64)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="workshop.client",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="workshop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketingPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("day", models.CharField(max_length=16)),
                ("month_label", models.CharField(max_length=64)),
                ("text", models.TextField()),
                ("channels", models.JSONField(default=list)),
                ("publish_time", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Черновик", "Черновик"),
                            ("Запланирован", "Запланирован"),
                            ("Опубликован", "Опубликован"),
                            ("Ошибка", "Ошибка"),
                        ],
                        default="Черновик",
                        max_length=32,
                    ),
                ),
                ("color_class", models.CharField(blank=True, max_length=64)),
                ("published_url", models.URLField(blank=True, max_length=1000)),
                ("error_message", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="workshop.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinanceCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("calculation_date", models.CharField(max_length=64)),
                ("product_name", models.CharField(max_length=255)),
                ("material", models.CharField(max_length=128)),
                ("weight", models.CharField(max_length=64)),
                ("hours", models.CharField(max_length=64)),
                ("cost", models.CharField(max_length=64)),
                ("markup", models.CharField(max_length=64)),
                ("total", models.CharField(max_length=64)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculations",
                        to="workshop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculations",
                        to="workshop.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.CharField(max_length=128)),
                ("text", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("review_date", models.CharField(blank=True, max_length=64)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="workshop.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
