# Generated by Django 5.2.1 on 2026-05-04 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="client",
        ),
        migrations.RemoveField(
            model_name="order",
            name="client",
        ),
        migrations.RemoveField(
            model_name="financecalculation",
            name="order",
        ),
        migrations.RemoveField(
            model_name="financecalculation",
            name="product",
        ),
        migrations.RemoveField(
            model_name="marketingpublication",
            name="product",
        ),
        migrations.DeleteModel(
            name="MaterialReference",
        ),
        migrations.RemoveField(
            model_name="message",
            name="order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="FinanceCalculation",
        ),
        migrations.DeleteModel(
            name="MarketingPublication",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
