# Generated by Django 5.2.1 on 2026-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0002_remove_crm_finance_marketing_add_audit_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("vk_url", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Потенциальный", "Потенциальный"),
                            ("Действующий", "Действующий"),
                            ("Завершён", "Завершён"),
                        ],
                        default="Потенциальный",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Colleague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("Дерево", "Дерево"),
                            ("Плечи", "Плечи"),
                            ("Железо", "Железо"),
                            ("Броня", "Броня"),
                        ],
                        max_length=32,
                    ),
                ),
                ("specialization", models.CharField(max_length=255)),
                ("contact", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["direction", "name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("Материал", "Материал"), ("Расходник", "Расходник")],
                        max_length=32,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("Дерево", "Дерево"),
                            ("Плечи", "Плечи"),
                            ("Железо", "Железо"),
                            ("Броня", "Броня"),
                        ],
                        max_length=32,
                    ),
                ),
                ("unit", models.CharField(max_length=32)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "min_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("supplier", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["direction", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_name", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=255)),
                ("configuration", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Новый", "Новый"),
                            ("В работе", "В работе"),
                            ("Выполнен", "Выполнен"),
                            ("Отменён", "Отменён"),
                        ],
                        default="Новый",
                        max_length=32,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("total", models.PositiveIntegerField(default=0)),
                ("advance", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
