# Generated by Django 5.2.1 on 2026-05-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_order_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="workshop.product",
            ),
        ),
    ]
