# Generated by Django 5.2.14 on 2026-05-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0006_vkpost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("В наличии", "В наличии"),
                    ("Изготовим на заказ", "Изготовим на заказ"),
                    ("Снят с производства", "Снят с производства"),
                ],
                max_length=32,
            ),
        ),
    ]
