# Generated by Django 5.2.14 on 2026-05-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workshop",
            "0007_order_assigned_to_order_client_vk_order_order_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productset",
            name="price_from",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
