# Generated by Django 5.2.14 on 2026-05-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0008_productset_price_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AddField(
            model_name="review",
            name="photo_url",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="review",
            name="vk_url",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="workshop.product",
            ),
        ),
    ]
