# Generated by Django 5.2.1 on 2026-05-27 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0013_productset_discount_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
        migrations.AlterField(
            model_name="productset",
            name="price_from",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Итоговая цена комплекта (если задана — скидка вычисляется из неё)",
                null=True,
            ),
        ),
    ]
