# Generated by Django 5.2.1 on 2026-05-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0014_alter_order_assigned_to_alter_productset_price_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deadline",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Новый", "Новый"),
                    ("В работе", "В работе"),
                    ("Выполнен", "Выполнен"),
                    ("Отменён", "Отменён"),
                ],
                db_index=True,
                default="Новый",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("taken", "Взята"),
                    ("done", "Выполнена"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
