import type { Product, Review, SortMode, ProductStatus } from './types';

export const fallbackProducts: Product[] = [
  {
    id: '1',
    name: 'Готический латный доспех',
    subtitle: 'Полный комплект для пешего боя, XV век',
    status: 'Под заказ',
    category: 'Полные комплекты',
    era: 'XV век',
    material: 'Сталь',
    sizes: ['M', 'L', 'XL'],
    priceFrom: 215000,
    leadTime: '6-8 недель',
    weight: '24 кг',
    popularity: 98,
    protectionClass: 'Высший',
    history: 'Классический образец германской оружейной школы XV века с каннелюрами, усиливающими листы стали и подчёркивающими силуэт латника.',
    description: [
      'Комплект собран по мотивам музейных оригиналов конца XV века и адаптирован под реконструкторскую практику. В него входят саллет, бувигер, кираса с плакартом, наплечники, латная защита рук и ног.',
      'Конструкция опирается на систему скользящих заклёпок, чтобы сохранить подвижность бойца во время пешего строя и показательных поединков. Внутренняя сторона обрабатывается антикоррозийным составом.',
      'Ременная система выполняется из кожи растительного дубления. Каждое изделие куётся под заказ и подгоняется по индивидуальным меркам владельца.',
    ],
    image: 'https://images.unsplash.com/photo-1732198678426-00f5ba98e5b5?auto=format&fit=crop&w=900&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1732198678426-00f5ba98e5b5?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1596716148130-f95f2b735a92?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1755359494724-7d9f74874275?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1734122373993-36745ac6b688?auto=format&fit=crop&w=900&q=80',
    ],
    badge: 'Новинка',
  },
  {
    id: '2',
    name: 'Шлем-саллет с забралом',
    subtitle: 'Позднесредневековый шлем, XV век',
    status: 'Готовый комплект',
    category: 'Шлемы',
    era: 'XV век',
    material: 'Сталь',
    sizes: ['M', 'L'],
    priceFrom: 48000,
    leadTime: 'В наличии',
    weight: '3.8 кг',
    popularity: 85,
    protectionClass: 'Высокий',
    history: 'Саллет распространился в германских и итальянских землях как универсальный шлем для пехоты и тяжёлой конницы.',
    description: [
      'Шлем выполнен с подвижным забралом и усиленным затылочным хвостом. Подходит для реконструкции позднего Средневековья и бугуртных тренировок.',
      'Внутри предусмотрена мягкая подвесная система и подбородочный ремень. Возможна настройка толщины стали под формат использования.',
    ],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Helmet%20(Sallet)%20MET%20DP160368.jpg',
    gallery: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Helmet%20(Sallet)%20MET%20DP160368.jpg',
      'https://commons.wikimedia.org/wiki/Special:FilePath/GermanBascinet1400.jpg',
      'https://commons.wikimedia.org/wiki/Special:FilePath/Barbute%20MET%2049.163.2%20005AA2015.jpg',
    ],
  },
  {
    id: '3',
    name: 'Миланский нагрудник',
    subtitle: 'Защита корпуса для турнирного строя, XV век',
    status: 'Готовый комплект',
    category: 'Нагрудники',
    era: 'XV век',
    material: 'Латунь и сталь',
    sizes: ['M', 'L'],
    priceFrom: 72000,
    leadTime: '10 дней',
    weight: '7.2 кг',
    popularity: 92,
    protectionClass: 'Высший',
    history: 'Миланская традиция отличалась гладкими крупными плоскостями и визуальной цельностью силуэта.',
    description: [
      'Нагрудник рассчитан на турнирное и показательное применение, с усилением в верхней части груди и надёжной развесовкой по корпусу.',
      'Доступны декоративные латунные акценты и индивидуальная полировка для витринных комплектов.',
    ],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cuirass%20and%20Tassets%20(Torso%20and%20Hip%20Defense)%20MET%20DP258634.jpg',
    gallery: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Cuirass%20and%20Tassets%20(Torso%20and%20Hip%20Defense)%20MET%20DP258634.jpg',
      'https://images.unsplash.com/photo-1732198678426-00f5ba98e5b5?auto=format&fit=crop&w=900&q=80',
      'https://commons.wikimedia.org/wiki/Special:FilePath/Helmet%20(Sallet)%20MET%20DP160368.jpg',
    ],
    badge: 'Полевые испытания',
  },
  {
    id: '4',
    name: 'Клёпаные рукавицы',
    subtitle: 'Защита кисти и предплечья, XIV век',
    status: 'Реконструкция',
    category: 'Рукавицы',
    era: 'XIV век',
    material: 'Комбинированный',
    sizes: ['S', 'M', 'L'],
    priceFrom: 39000,
    leadTime: '3-4 недели',
    weight: '2.1 кг',
    popularity: 74,
    protectionClass: 'Средний',
    history: 'Клёпаные рукавицы встречались в позднесредневековых комплектах как компромисс между гибкостью и защитой.',
    description: ['Рукавицы собираются на кожаной основе с металлическими сегментами и могут комплектоваться внутренней варежкой.'],
    image: 'https://i2.storeland.net/1/4375/43746231/afacdb/varezhka-kolchuzhnaya-klpano-sechnaya.jpg',
    gallery: [
      'https://i2.storeland.net/1/4375/43746231/afacdb/varezhka-kolchuzhnaya-klpano-sechnaya.jpg',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: '5',
    name: 'Кольчужный хауберт',
    subtitle: 'Реконструкция походного доспеха, XIII век',
    status: 'Под заказ',
    category: 'Полные комплекты',
    era: 'XIII век',
    material: 'Сталь',
    sizes: ['M', 'L', 'XL'],
    priceFrom: 96000,
    leadTime: '5-6 недель',
    weight: '12 кг',
    popularity: 89,
    protectionClass: 'Средний',
    history: 'Хауберт был основой рыцарского защитного комплекса до широкого распространения латных доспехов.',
    description: ['Плетение выполняется из клёпаных и сварных колец по историческим аналогам. Возможно изготовление с капюшоном и рукавицами.'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Italian%20-%20Mail%20-%20Walters%2051575.jpg',
    gallery: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Italian%20-%20Mail%20-%20Walters%2051575.jpg',
      'https://images.unsplash.com/photo-1732198678426-00f5ba98e5b5?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: '6',
    name: 'Турнирный щит павеза',
    subtitle: 'Крупный щит с кожаной обтяжкой, XV век',
    status: 'Под заказ',
    category: 'Щиты',
    era: 'XV век',
    material: 'Кожа',
    sizes: ['M', 'L'],
    priceFrom: 36000,
    leadTime: '2-3 недели',
    weight: '5.4 кг',
    popularity: 68,
    protectionClass: 'Высокий',
    history: 'Павезы использовались как полевые укрытия и крупные строевые щиты в позднесредневековых кампаниях.',
    description: ['Щит формуется на деревянной основе, обтягивается кожей и подготавливается под роспись или геральдику заказчика.'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Royal%20Armouries%20-%20Up%20Close%20online%20exhibition%20-%20Detail%20of%20pavise,%2015th%20century,%20V.10%20(53528248681).jpg',
    gallery: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Royal%20Armouries%20-%20Up%20Close%20online%20exhibition%20-%20Detail%20of%20pavise,%2015th%20century,%20V.10%20(53528248681).jpg',
      'https://images.unsplash.com/photo-1732198678426-00f5ba98e5b5?auto=format&fit=crop&w=900&q=80',
    ],
    badge: 'Новинка',
  },
  {
    id: '7',
    name: 'Бацинет с бармицей',
    subtitle: 'Боевой шлем для XIV века, реконструкция под размер M',
    status: 'Под заказ',
    category: 'Шлемы',
    era: 'XIV век',
    material: 'Сталь',
    sizes: ['S', 'M'],
    priceFrom: 54000,
    leadTime: '4-5 недель',
    weight: '4.1 кг',
    popularity: 81,
    protectionClass: 'Высокий',
    history: 'Бацинет стал одной из самых узнаваемых форм защиты головы в XIV веке, постепенно вытесняя более ранние формы шлемов.',
    description: [
      'Модель рассчитана на историческую реконструкцию с кольчужной бармицей и внутренней подвесной системой.',
      'Подходит для демонстрационных выходов и тренировочного формата с индивидуальной подгонкой по окружности головы.',
    ],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/GermanBascinet1400.jpg',
    gallery: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/GermanBascinet1400.jpg',
      'https://commons.wikimedia.org/wiki/Special:FilePath/Helmet%20(Sallet)%20MET%20DP160368.jpg',
      'https://images.unsplash.com/photo-1732198678426-00f5ba98e5b5?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: '8',
    name: 'Барбута "Марсово поле"',
    subtitle: 'Открытый шлем итальянского типа, XV век',
    status: 'Готовый комплект',
    category: 'Шлемы',
    era: 'XV век',
    material: 'Сталь',
    sizes: ['M'],
    priceFrom: 51000,
    leadTime: '7 дней',
    weight: '3.5 кг',
    popularity: 79,
    protectionClass: 'Высокий',
    history: 'Барбута отсылает к античным силуэтам и особенно характерна для итальянских мастерских XV века.',
    description: [
      'Шлем сохраняет открытое лицо и хороший обзор, поэтому удобен для показательных выступлений и фестивалей.',
      'Поверхность отполирована до мягкого сатинового блеска, возможна отделка латунной кромкой.',
    ],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Barbute%20MET%2049.163.2%20005AA2015.jpg',
    gallery: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Barbute%20MET%2049.163.2%20005AA2015.jpg',
      'https://commons.wikimedia.org/wiki/Special:FilePath/Helmet%20(Sallet)%20MET%20DP160368.jpg',
      'https://images.unsplash.com/photo-1734122373993-36745ac6b688?auto=format&fit=crop&w=900&q=80',
    ],
    badge: 'Новинка',
  },
];

export const fallbackReviews: Record<string, Review[]> = {
  '2': [
    {
      author: 'Илья, клуб "Северный гарнизон"',
      text: 'Шлем сел точно по мерке, обзор хороший, внутренняя подвеска выдержала весь фестивальный сезон.',
      rating: 5,
      date: '12.01.2026',
    },
  ],
  '8': [
    {
      author: 'Алексей',
      text: 'Очень аккуратная полировка и комфортная посадка. Для формата фестиваля оказался отличным вариантом.',
      rating: 4,
      date: '03.02.2026',
    },
  ],
};

export const sortOptions: { value: SortMode; label: string }[] = [
  { value: 'default', label: 'По умолчанию' },
  { value: 'newest', label: 'Сначала новые' },
  { value: 'popular', label: 'По популярности' },
  { value: 'duration', label: 'По сроку изготовления' },
];

export const statusStyles: Record<ProductStatus, string> = {
  'Готовый комплект': 'status status-ready',
  'Под заказ': 'status status-order',
  'Реконструкция': 'status status-reconstruction',
};

export const sidebarSections = [
  {
    title: 'Каталог доспехов',
    links: ['Готовые работы', 'Реконструкция по источникам', 'Турнирные комплекты', 'Отдельные элементы'],
  },
  {
    title: 'Услуги мастерской',
    links: ['Подгонка по меркам', 'Ремонт и реставрация', 'Историческая консультация', 'Финишная отделка'],
  },
];

export const filterSections = [
  { key: 'categories', title: 'Тип доспеха', options: ['Шлемы', 'Нагрудники', 'Полные комплекты', 'Аксессуары', 'Щиты', 'Рукавицы'] },
  { key: 'eras', title: 'Эпоха', options: ['XIII век', 'XIV век', 'XV век', 'XVI век'] },
  { key: 'materials', title: 'Материал', options: ['Сталь', 'Кожа', 'Комбинированный', 'Латунь и сталь'] },
  { key: 'sizes', title: 'Размер', options: ['XS', 'S', 'M', 'L', 'XL'] },
  { key: 'statuses', title: 'Статус', options: ['Готовый комплект', 'Под заказ', 'Реконструкция'] },
] as const;
